--[[
    Horizon Suite - Insight - SetDB routing keys
    Exports INSIGHT_KEYS used by OptionsData_SetDB to trigger
    Insight.ApplyInsightOptions when any Insight tooltip setting changes.
]]
local addon = _G.HorizonSuite
if not addon then return end

addon.INSIGHT_KEYS = {
    insightAnchorMode            = true,
    insightCursorSide            = true,
    insightFixedPoint            = true,
    insightFixedX                = true,
    insightFixedY                = true,
    insightCursorOffsetX         = true,
    insightCursorOffsetY         = true,
    insightFocusDynamicInFixed   = true,
    insightHideTooltipsInCombat  = true,
    insightBgOpacity             = true,
    insightShowMount             = true,
    insightShowIlvl              = true,
    insightItemLevelMode         = true,
    insightShowSpecRole          = true,
    insightShowCharacterTitle    = true,
    insightRealmNameMode         = true,
    insightRaceIcons             = true,
    insightPlayerNameColor       = true,
    insightPlayerNameGradient    = true,
    insightTitleColorMode        = true,
    insightTitleMatchNameColor   = true,
    insightTitleColor            = true,
    insightTitleColorR           = true,
    insightTitleColorG           = true,
    insightTitleColorB           = true,
    insightShowHonorLevel        = true,
    insightHonorLevelMode        = true,
    insightAchievementPointsMode = false,
    insightShowStatusBadges      = true,
    insightStatusBadgeCombat     = true,
    insightStatusBadgeAFK        = true,
    insightStatusBadgeDND        = true,
    insightStatusBadgePVP        = true,
    insightStatusBadgeGroup      = true,
    insightStatusBadgeFriend     = true,
    insightStatusBadgeTargeting  = true,
    insightShowMythicScore       = true,
    insightMythicScoreMode       = true,
    insightRatingsIcons          = true,
    insightShowTransmog          = true,
    insightShowGuildRank         = true,
    insightSeparatorMode         = true,
    insightBlankSeparator        = true,
    insightShowIcons             = true,
    insightClassIconSource       = true,
    insightFontPath              = true,
    insightHeaderSize            = true,
    insightBodySize              = true,
    insightBadgesSize            = true,
    insightStatsSize             = true,
    insightMountSize             = true,
    insightTransmogSize          = true,
    insightMountOwnershipDisplay = true,
    -- NPC tooltip
    insightNpcReactionBorder     = true,
    insightNpcReactionName       = true,
    insightNpcShowLevelLine      = true,
    insightNpcShowIcons          = true,
    insightNpcHeaderSize         = true,
    insightNpcBodySize           = true,
    -- Item tooltip
    insightItemQualityBorder     = true,
    insightItemNameGradient      = true,
    insightItemSectionSpacing    = true,
    insightItemHeaderSize        = true,
    insightItemBodySize          = true,
    insightItemTransmogSize      = true,
    -- Player tooltip (per-type font sizes)
    insightPlayerHeaderSize      = true,
    insightPlayerBodySize        = true,
    insightPlayerBadgesSize      = true,
    insightPlayerStatsSize       = true,
    insightPlayerMountSize       = true,
}
