--[[
    Horizon Suite - Dashboard news feed.
    GENERATED by tools/build_news.py from news/*.md. Do not edit this file:
    edit or add a story in news/ and run `python3 tools/build_news.py`.
]]

local addon = _G.HorizonSuite

addon.DashboardNewsFeed = {
    {
        id = "axis-settings-refresh",
        title = "A tidier settings dashboard",
        layout = "featured",
        priority = 500,
        fromDate = "2026-10-06",
        untilDate = "2026-12-31",
        image = "Interface/AddOns/HorizonSuite/media/news/axis-settings-refresh.png",
        button = "Open settings",
        action = { type = "module", moduleKey = "axis" },
        paragraphs = {
            "Every on-screen element now has one card, with its switch at the top and everything else for it underneath.",
            "Search understands typos and synonyms, and remembers what you looked for.",
        },
    },
}
