--[[
    Horizon Suite - Dashboard news feed.
    GENERATED by tools/build_news.py from news/*.md. Do not edit this file:
    edit or add a story in news/ and run `python3 tools/build_news.py`.
]]

local addon = _G.HorizonSuite

addon.DashboardNewsFeed = {
    {
        id = "settings-rebuilt-6-7",
        title = "6.7.0: a rebuilt settings dashboard",
        layout = "featured",
        priority = 500,
        fromDate = "2026-10-09",
        untilDate = "2026-12-08",
        image = "Interface/AddOns/HorizonSuite/media/news/settings-rebuilt-6-7.png",
        button = "Open settings",
        action = { type = "module", moduleKey = "axis" },
        button2 = "Module guide",
        action2 = { type = "guide" },
        modules = { "axis" },
        summary = "Version 6.7.0 rebuilds the settings dashboard so every setting sits with the thing it changes.",
        blocks = {
            { kind = "p", text = "Version 6.7.0 rebuilds the settings dashboard so every setting sits with the thing it changes." },
            { kind = "list", items = { "|cffffffffOne card per element:|r each on-screen element has its switch at the top and everything for it underneath, in every module.", "Search forgives typos, understands synonyms and remembers what you looked for.", "Sub-settings slide in when you turn their switch on, and a marker shows which settings you have changed from their defaults.", "A new Welcome page, matching module icons, and News stories you can open." } },
        },
        paragraphs = {
            "Version 6.7.0 rebuilds the settings dashboard so every setting sits with the thing it changes.",
        },
    },
}
