#!/usr/bin/env python3
"""Compile news/*.md into options/dashboard/DashboardNewsFeed.lua.

Each story is one Markdown file with a front matter block (see news/README.md).
The generated Lua is committed so a branch pulled onto a test PC shows the same
news a release will; CI runs --check so a story edited without a rebuild fails.

Usage:
  python3 tools/build_news.py          # rebuild the feed
  python3 tools/build_news.py --check  # exit 1 if the committed feed is stale

Exit codes: 0 ok, 1 stale (--check), 2 invalid story. Standard library only.
"""
import argparse
import datetime
import os
import re
import struct
import sys

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DEFAULT_NEWS = os.path.join(REPO, "news")
DEFAULT_MEDIA = os.path.join(REPO, "media", "news")
DEFAULT_OUT = os.path.join(REPO, "options", "dashboard", "DashboardNewsFeed.lua")
TEXTURE_PREFIX = "Interface/AddOns/HorizonSuite/media/news/"

MODULE_KEYS = {"axis", "focus", "presence", "vista", "insight", "augment", "essence", "echo"}
FIELDS = {"id", "title", "layout", "priority", "from", "until", "untilVersion",
          "image", "button", "action"}
ID_RE = re.compile(r"^[a-z0-9]+(-[a-z0-9]+)*$")
VERSION_RE = re.compile(r"^\d+(\.\d+){0,3}$")
MAX_TITLE = 60
MAX_IMAGE = 1024

HEADER = """--[[
    Horizon Suite - Dashboard news feed.
    GENERATED by tools/build_news.py from news/*.md. Do not edit this file:
    edit or add a story in news/ and run `python3 tools/build_news.py`.
]]

local addon = _G.HorizonSuite

"""


class StoryError(Exception):
    pass


def parse_story(name, text):
    text = text.replace("\r\n", "\n").lstrip("﻿")
    if not text.startswith("---\n"):
        raise StoryError(f"{name}: must start with a '---' front matter line")
    end = text.find("\n---\n", 3)
    if end < 0:
        raise StoryError(f"{name}: front matter has no closing '---' line")
    meta = {}
    for n, line in enumerate(text[4:end].split("\n"), start=2):
        if not line.strip():
            continue
        key, sep, value = line.partition(":")
        key, value = key.strip(), value.strip()
        if not sep:
            raise StoryError(f"{name}:{n}: expected 'key: value'")
        if key not in FIELDS:
            raise StoryError(f"{name}:{n}: unknown field '{key}'")
        if key in meta:
            raise StoryError(f"{name}:{n}: duplicate field '{key}'")
        meta[key] = value
    body = text[end + 5:]
    paragraphs = [" ".join(p.split()) for p in re.split(r"\n\s*\n", body) if p.strip()]
    return meta, paragraphs


def png_size(path):
    with open(path, "rb") as fh:
        head = fh.read(24)
    if len(head) < 24 or head[:8] != b"\x89PNG\r\n\x1a\n" or head[12:16] != b"IHDR":
        return None
    return struct.unpack(">II", head[16:24])


def parse_date(name, field, value):
    try:
        datetime.date.fromisoformat(value)
    except ValueError:
        raise StoryError(f"{name}: '{field}' must be a real date as YYYY-MM-DD, got '{value}'")
    if len(value) != 10:
        raise StoryError(f"{name}: '{field}' must be YYYY-MM-DD, got '{value}'")
    return value


def parse_action(name, value):
    kind, _, arg = value.partition(" ")
    arg = arg.strip()
    if kind == "module":
        if arg not in MODULE_KEYS:
            raise StoryError(f"{name}: unknown module '{arg}' (use one of {', '.join(sorted(MODULE_KEYS))})")
        return [("type", "module"), ("moduleKey", arg)]
    if kind in ("patch_notes", "news", "guide") and not arg:
        return [("type", kind)]
    if kind == "url":
        if not arg.startswith("https://") or " " in arg:
            raise StoryError(f"{name}: a url action needs one https:// address")
        return [("type", "copy_url"), ("url", arg)]
    raise StoryError(f"{name}: unknown action '{value}' (module <key>, patch_notes, news, guide, url <https://...>)")


def validate(name, meta, paragraphs, media_dir):
    for req in ("id", "title"):
        if not meta.get(req):
            raise StoryError(f"{name}: missing required field '{req}'")
    sid = meta["id"]
    if not ID_RE.match(sid):
        raise StoryError(f"{name}: id '{sid}' must be lowercase letters, digits and hyphens")
    if name != sid + ".md":
        raise StoryError(f"{name}: id '{sid}' must match the file name ({sid}.md)")
    if len(meta["title"]) > MAX_TITLE:
        raise StoryError(f"{name}: title is longer than {MAX_TITLE} characters")
    story = {"id": sid, "title": meta["title"]}
    layout = meta.get("layout", "card")
    if layout not in ("card", "featured"):
        raise StoryError(f"{name}: layout must be 'card' or 'featured', got '{layout}'")
    story["layout"] = layout
    priority = meta.get("priority", "100")
    if not re.match(r"^-?\d+$", priority):
        raise StoryError(f"{name}: priority must be a whole number, got '{priority}'")
    story["priority"] = int(priority)
    if "from" in meta:
        story["fromDate"] = parse_date(name, "from", meta["from"])
    if "until" in meta:
        story["untilDate"] = parse_date(name, "until", meta["until"])
    if "fromDate" in story and "untilDate" in story and story["untilDate"] < story["fromDate"]:
        raise StoryError(f"{name}: 'until' is before 'from'")
    if "untilVersion" in meta:
        if not VERSION_RE.match(meta["untilVersion"]):
            raise StoryError(f"{name}: untilVersion must look like 6.6.0, got '{meta['untilVersion']}'")
        story["untilVersion"] = meta["untilVersion"]
    if "image" in meta:
        img = meta["image"]
        path = os.path.join(media_dir, img)
        if "/" in img or "\\" in img or not os.path.isfile(path):
            raise StoryError(f"{name}: image '{img}' not found in media/news/")
        size = png_size(path)
        if size is None:
            raise StoryError(f"{name}: image '{img}' is not a PNG")
        for dim in size:
            if dim > MAX_IMAGE:
                raise StoryError(f"{name}: image '{img}' is {size[0]}x{size[1]}; the limit is {MAX_IMAGE}")
            if dim & (dim - 1):
                raise StoryError(f"{name}: image '{img}' is {size[0]}x{size[1]}; each side must be a power of two")
        story["image"] = TEXTURE_PREFIX + img
    elif layout == "featured":
        raise StoryError(f"{name}: a featured story needs an image")
    if ("button" in meta) != ("action" in meta):
        raise StoryError(f"{name}: give both 'button' and 'action', or neither")
    if "button" in meta:
        story["button"] = meta["button"]
        story["action"] = parse_action(name, meta["action"])
    if not paragraphs:
        raise StoryError(f"{name}: story has no text")
    story["paragraphs"] = paragraphs
    return story


def lua_str(s):
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"').replace("|", "||") + '"'


def emit(stories):
    out = [HEADER, "addon.DashboardNewsFeed = {\n"]
    for s in stories:
        out.append("    {\n")
        for key in ("id", "title", "layout"):
            out.append(f"        {key} = {lua_str(s[key])},\n")
        out.append(f"        priority = {s['priority']},\n")
        for key in ("fromDate", "untilDate", "untilVersion", "image", "button"):
            if key in s:
                out.append(f"        {key} = {lua_str(s[key])},\n")
        if "action" in s:
            parts = ", ".join(f"{k} = {lua_str(v)}" for k, v in s["action"])
            out.append(f"        action = {{ {parts} }},\n")
        out.append("        paragraphs = {\n")
        for p in s["paragraphs"]:
            out.append(f"            {lua_str(p)},\n")
        out.append("        },\n    },\n")
    out.append("}\n")
    return "".join(out)


def build(news_dir, media_dir):
    stories = []
    names = sorted(n for n in os.listdir(news_dir) if n.endswith(".md") and n != "README.md") \
        if os.path.isdir(news_dir) else []
    for name in names:
        with open(os.path.join(news_dir, name), encoding="utf-8") as fh:
            meta, paragraphs = parse_story(name, fh.read())
        stories.append(validate(name, meta, paragraphs, media_dir))
    return emit(stories)


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--check", action="store_true", help="exit 1 if the feed file is stale")
    ap.add_argument("--news", default=DEFAULT_NEWS)
    ap.add_argument("--media", default=DEFAULT_MEDIA)
    ap.add_argument("--out", default=DEFAULT_OUT)
    args = ap.parse_args(argv)
    try:
        lua = build(args.news, args.media)
    except StoryError as e:
        print(f"build_news: {e}", file=sys.stderr)
        return 2
    if args.check:
        try:
            with open(args.out, "rb") as fh:
                current = fh.read().decode("utf-8").replace("\r\n", "\n")
        except FileNotFoundError:
            current = None
        if current != lua:
            print(f"build_news: {os.path.relpath(args.out, REPO)} is out of date; "
                  "run `python3 tools/build_news.py` and commit the result", file=sys.stderr)
            return 1
        return 0
    with open(args.out, "wb") as fh:
        fh.write(lua.replace("\n", "\r\n").encode("utf-8"))
    return 0


if __name__ == "__main__":
    sys.exit(main())
